# Generated by Django 3.1 on 2020-09-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='xcategory',
            field=models.CharField(default='game comparison', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(default='action', help_text='All lowercase', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
    ]
