# Generated by Django 3.1 on 2020-09-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200905_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='popular',
            field=models.BooleanField(null=True),
        ),
    ]
