# Generated by Django 3.1 on 2020-09-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('polls', '0005_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='left',
            field=models.IntegerField(default=20),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
