# Generated by Django 3.1 on 2020-09-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200907_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image2',
            field=models.ImageField(blank=True, upload_to='polls/images/'),
        ),
        migrations.AddField(
            model_name='new',
            name='image3',
            field=models.ImageField(blank=True, upload_to='polls/images/'),
        ),
    ]
