# Generated by Django 3.1 on 2020-09-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200907_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='image2text',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
